# Generated by Django 4.0.4 on 2022-05-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='study_and_condition',
            new_name='diagnostico',
        ),
    ]
